workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

image: python:3.7

stages:
  - lint
  - test

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

# Линтеры
mypy:
  stage: lint
  script:
    - mypy .

black:
  stage: lint
  script:
    - black --diff --check .

isort:
  stage: lint
  script:
    - isort --check-only .

flake8:
  stage: lint
  script:
    - flake8 .

unittest:
  stage: test
  script:
    - pytest --maxfail=1 --disable-warnings
