[tool.black]
line-length = 88
target-version = ["py312"]
extend-exclude = "(^|/)(\\.venv|venv|env|new_env|\\.tox|build|dist|pycache|site-packages)(/|$)"

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["database", "main", "test_main"]
src_paths = ["."]
skip = [".venv", "venv", "env", "new_env", ".tox", "build", "dist", ".git"]
skip_glob = ["/site-packages/", "/__pycache__/"]
